version: '3.1'

services:
  postgres:
    image: postgres:9.6-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "poeladder" 
  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080