leagues:
   currentLeagues: 
    - Synthesis
    - Hardcore Synthesis
    - SSF Synthesis
    - SSF Synthesis HC


datatables:
   topfive:
      delve: 
         tableColumns:
          - '#'
          - Character
          - Asc
          - Dept